# .travis.yml
language: python 
services:
  - docker  

stages:
  - lint
  - build
  # - test
  # - deploy

env:
  global:
    - DOCKER_REPO=liyaimages/liya-images
    - COMMIT_TAG=${TRAVIS_COMMIT:0:7}
    - LATEST_TAG=latest

jobs:
  include:

    - stage: lint
      name: "Flake8 linting"
      install:
        - pip install flake8       
      script:
        - echo "Running linter"
        - flake8 app/
    
    - stage: "build"                # naming the Tests stage
      name: "build docker image for application"            # names the first Tests stage job
      script:
        - echo "Building $DOCKER_REPO:$COMMIT_TAG"
        - docker build -t $DOCKER_REPO:$COMMIT_TAG -f Dockerfile .
        - docker tag $DOCKER_REPO:$COMMIT_TAG $DOCKER_REPO:$LATEST_TAG
