# .travis.yml
language: python 
services:
  - docker  

stages:
  - lint
  - build
  - test
  # - deploy

env:
  global:
    - DOCKER_REPO=liyaimages/liya-images
    - COMMIT_TAG=${TRAVIS_COMMIT:0:7}
    - LATEST_TAG=latest
    - PORT=5000

jobs:
  include:
    - stage: lint
      name: "Flake8 linting"
      install:
        - pip install flake8       
      script:
        - echo "Running linter"
        - flake8 app/
    
    - stage: "build"                # naming the Tests stage
      name: "build docker image for application"            # names the first Tests stage job
      script:
        - echo "Building $DOCKER_REPO:$COMMIT_TAG"
        - docker build -t $DOCKER_REPO:$COMMIT_TAG -f Dockerfile .
        - docker tag $DOCKER_REPO:$COMMIT_TAG $DOCKER_REPO:$LATEST_TAG


    - stage: "test" 
      name: "build the docker container and test the app"  
      install:
        - pip install pytest
      before_script:
        - echo "building the docker container with image $DOCKER_REPO:$COMMIT_TAG"
        - RUN_OPTS="-e PORT=$PORT -p $PORT:$PORT \
              -e AWS_REGION=$AWS_REGION -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
              -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e CODE_NAME=$CODE_NAME " 
        - docker run $RUN_OPTS -dit $DOCKER_REPO:$COMMIT_TAG
      script:
        - echo "Running pytest"
        - pytest --maxfail=1 --disable-warnings -q tests/*


