# .travis.yml
language: python 
services:
  - docker  

stages:
  - lint
  - test
  - build and push

env:
  global:
    - DOCKER_REPO=liyaimages/liya-images/devops-challenge
    - COMMIT_TAG=${TRAVIS_COMMIT:0:7}
    - LATEST_TAG=latest
    - PORT=5000

jobs:
  include:
    - stage: lint
      name: "Flake8 linting"
      install:
        - pip install flake8       
      script:
        - echo "Running linter"
        - flake8 app/
  

    - stage: "test" 
      name: "build the docker container and test the app"  
      install:
        - pip install pytest requests
      before_script:
        - echo "Building $DOCKER_REPO:$COMMIT_TAG"
        - docker build -t $DOCKER_REPO:$COMMIT_TAG -f Dockerfile .
        - echo "building the docker container with image $DOCKER_REPO:$COMMIT_TAG"
        - docker run -e PORT="$PORT" -p "$PORT:$PORT" -e AWS_REGION="$AWS_REGION" -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" -e CODE_NAME="$CODE_NAME" -e DOCKERHUB_URL="$DOCKERHUB_URL" -e GITHUB_PROJECT="$GITHUB_PROJECT" -dit "$DOCKER_REPO:$COMMIT_TAG"
        - sleep 2
      script:
        - echo "Running pytest"
        - pytest --maxfail=1 --disable-warnings -q tests/*
      after_failure:
        - echo "Tests failed removing the docker image and container" 


    - stage: "build and push"
      name: "deploy to docker hub"
      script:
        - echo "Building $DOCKER_REPO:$COMMIT_TAG"
        - docker build -t $DOCKER_REPO:$COMMIT_TAG -f Dockerfile .
        - echo "Pushing $DOCKER_REPO:$COMMIT_TAG to Docker Hub"
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker tag $DOCKER_REPO:$COMMIT_TAG $DOCKER_REPO:$LATEST_TAG
        - docker push $DOCKER_REPO:$COMMIT_TAG
        - docker push $DOCKER_REPO:$LATEST_TAG


