services:
  api:
    build:              
      context: .                  
      dockerfile: Dockerfile

    container_name: secret-api
    env_file:               
      - .env                       
    ports:
      - "${PORT:-5000}:${PORT:-5000}"

    restart: unless-stopped